#ifndef ALIA_CORE_HPP
#define ALIA_CORE_HPP

#include <alia/core/actions/adaptors.hpp>
#include <alia/core/actions/basic.hpp>
#include <alia/core/actions/core.hpp>
#include <alia/core/actions/library.hpp>
#include <alia/core/actions/operators.hpp>
#include <alia/core/actions/signals.hpp>
#include <alia/core/common.hpp>
#include <alia/core/context/interface.hpp>
#include <alia/core/context/storage.hpp>
#include <alia/core/context/structural_typing.hpp>
#include <alia/core/flow/components.hpp>
#include <alia/core/flow/conditionals.hpp>
#include <alia/core/flow/content_caching.hpp>
#include <alia/core/flow/data_graph.hpp>
#include <alia/core/flow/events.hpp>
#include <alia/core/flow/for_each.hpp>
#include <alia/core/flow/macros.hpp>
#include <alia/core/flow/object_trees.hpp>
#include <alia/core/flow/try_catch.hpp>
#include <alia/core/flow/utilities.hpp>
#include <alia/core/id.hpp>
#include <alia/core/signals/adaptors.hpp>
#include <alia/core/signals/application.hpp>
#include <alia/core/signals/async.hpp>
#include <alia/core/signals/basic.hpp>
#include <alia/core/signals/containers.hpp>
#include <alia/core/signals/core.hpp>
#include <alia/core/signals/higher_order.hpp>
#include <alia/core/signals/lambdas.hpp>
#include <alia/core/signals/numeric.hpp>
#include <alia/core/signals/operators.hpp>
#include <alia/core/signals/state.hpp>
#include <alia/core/signals/text.hpp>
#include <alia/core/signals/utilities.hpp>
#include <alia/core/signals/validation.hpp>
#include <alia/core/system/interface.hpp>
#include <alia/core/system/internals.hpp>
#include <alia/core/timing/cubic_bezier.hpp>
#include <alia/core/timing/deflicker.hpp>
#include <alia/core/timing/scheduler.hpp>
#include <alia/core/timing/smoothing.hpp>
#include <alia/core/timing/ticks.hpp>
#include <alia/core/timing/timer.hpp>
#include <alia/core/timing/waves.hpp>

#endif
