#ifndef ALIA_ABI_UI_TEXT_H
#define ALIA_ABI_UI_TEXT_H

#include <alia/abi/base/color.h>
#include <alia/abi/base/geometry.h>
#include <alia/abi/context.h>
#include <alia/abi/kernel/signal.h>
#include <alia/abi/prelude.h>
#include <alia/abi/ui/drawing/primitives.h>
#include <alia/abi/ui/geometry.h>
#include <alia/abi/ui/layout/flags.h>
#include <alia/abi/ui/palette.h>
#include <alia/abi/ui/styling.h>

#include <string.h>

ALIA_EXTERN_C_BEGIN

// This file defines the Alia text system.

// Note that in Alia, a "typeface" is size-independent but includes all other
// typographic styling information (e.g. weight/slant/width). An example of a
// typeface might be "Roboto Regular". Meanwhile, a "font" is the combination
// of a typeface with a size (e.g., "Roboto Regular 12pt"). Neither of these is
// a "family" of fonts/typefaces (e.g., "Roboto"). This terminology is used
// consistently throughout Alia and generally aligns with technical usage in UI
// and typography, but it's important to note that it can conflict with common
// usage. For example, the information included in a modern "font file" (e.g.,
// `Roboto.ttf`) often spans what Alia would call a "family" of typefaces.

// A text engine is an opaque, pluggable implementation that turns runs of
// UTF-8 into measurable, drawable glyph data. The Alia core provides text
// components, flow layout integration, font metrics and style management,
// but it outsources the actual shaping and rendering to the engine. At the
// moment, the only available text engine is an ASCII/Latin MSDF engine, but
// the API itself is designed to support future engines with glyph caching and
// complex script handling.

typedef struct alia_text_engine_vtable alia_text_engine_vtable;

// base handle for an engine instance - Implementations embed this as their
// first member so the core can dispatch through `vtable`.
typedef struct alia_text_engine
{
    alia_text_engine_vtable const* vtable;
} alia_text_engine;

// an opaque, engine-owned "prepared text" object - This is a cache slot
// managed by the core text components. It's intended to allow the engine to
// cache the result of segmenting, shaping, and measuring a run of text at a
// given font/size.
typedef struct alia_text_block alia_text_block;

// a numeric typeface ID - IDs are assigned from a single continuous
// sequence in the core, so this is unique for the lifetime of the system. 0 is
// reserved as "invalid".
typedef uint32_t alia_typeface_id;
#define ALIA_TYPEFACE_ID_INVALID ((alia_typeface_id) 0)

// metrics for a font (a typeface at a size), in logical pixels - The global
// geometry scale factor is NOT applied here, so a "1 em" spacer is simply
// `em_size`. Note that these are generated by the engine individually for each
// font, so when working with multiple fonts from the same typeface, it's not
// guaranteed that these metrics will scale linearly with the font size.
typedef struct alia_font_metrics
{
    float em_size;
    float line_height;
    float ascender;
    float descender;
    float underline_y;
    float underline_thickness;
    float cap_height;
} alia_font_metrics;

// break-unit classification for a segment
typedef uint8_t alia_text_segment_kind;
enum
{
    // a measurable/drawable run (a "word")
    ALIA_TEXT_SEGMENT_CONTENT = 0,
    // inter-word whitespace (suppressible at line edges)
    ALIA_TEXT_SEGMENT_SPACE = 1,
    // an explicit hard break (newline)
    ALIA_TEXT_SEGMENT_HARD_BREAK = 2,
};

// content/placement direction for a segment or run
typedef uint8_t alia_text_direction;
enum
{
    ALIA_TEXT_DIRECTION_LTR = 0,
    ALIA_TEXT_DIRECTION_RTL = 1,
    ALIA_TEXT_DIRECTION_NEUTRAL = 2,
};

// a single break unit within a prepared block
typedef struct alia_text_segment
{
    // source byte range within the block's text
    size_t byte_start;
    size_t byte_end;
    // advance width at the block's font size
    float advance_width;
    alia_text_segment_kind kind;
    alia_text_direction direction;
} alia_text_segment;

// the engine contract
struct alia_text_engine_vtable
{
    // Fill `out` with the typeface's metrics at `size`, in logical pixels
    // (geometry scale is not applied). Size is passed so engines that vary
    // metrics by size (e.g. optical sizing) can honor it; simpler engines just
    // scale their em metrics by `size`.
    void (*get_font_metrics)(
        alia_text_engine* engine,
        void* engine_handle,
        float size,
        alia_font_metrics* out);

    // Segment, shape, and measure `utf8` into a prepared block. The engine
    // must copy any bytes it needs to retain, since the source may be
    // transient.
    alia_text_block* (*prepare_block)(
        alia_text_engine* engine,
        void* engine_handle,
        float font_size,
        alia_text_direction base_direction,
        char const* utf8,
        size_t length);

    void (*release_block)(alia_text_engine* engine, alia_text_block* block);

    int (*segment_count)(alia_text_engine* engine, alia_text_block* block);

    void (*segment_info)(
        alia_text_engine* engine,
        alia_text_block* block,
        int index,
        alia_text_segment* out);

    // Draw the glyphs covering `[byte_start, byte_end)` with the baseline
    // starting at `baseline_origin`.
    void (*draw_block_range)(
        alia_text_engine* engine,
        alia_context* ctx,
        alia_z_index z_index,
        alia_text_block* block,
        size_t byte_start,
        size_t byte_end,
        alia_vec2f baseline_origin,
        alia_srgba8 color,
        alia_text_direction direction);
};

// TYPEFACE REGISTRY

// a resolved typeface (what a typeface ID resolves to) - This is also the
// record the registry stores, so `id` is technically redundant within the
// registry itself, but carrying it makes a resolved typeface self-describing
// wherever it travels (identity checks, cache keys, debugging). It also leaves
// the door open for alternate registry implementations that might be more
// amenable to font churn (e.g. a hash table).
typedef struct alia_resolved_typeface
{
    // the app-side typeface ID
    alia_typeface_id id;
    // the text engine that owns this typeface
    alia_text_engine* engine;
    // the engine's private handle for this typeface
    void* engine_handle;
} alia_resolved_typeface;

// Register a typeface with the core and return an `alia_typeface_id`.
alia_typeface_id
alia_register_typeface(
    alia_ui_system* system, alia_text_engine* engine, void* engine_handle);

// Resolve a typeface ID to its registry record. The ID must be valid and
// registered; passing an invalid or unregistered ID is a programming error and
// asserts.
alia_resolved_typeface
alia_typeface_resolve(alia_ui_system* system, alia_typeface_id typeface);

// FONTS

// `alia_font` is the combination of a typeface ID and a size. This is the
// lightweight form that UI code uses to specify fonts or store them across
// frames.
typedef struct alia_font
{
    alia_typeface_id typeface;
    // logical (design) pixel size - Geometry scale is applied at layout/draw.
    float size;
} alia_font;

// `alia_resolve_font` is the cached result of resolving an `alia_font`. This
// is what gets activated, passed to components, and read for metrics.
// Resolution and activation are separate steps: the app resolves fonts on
// demand (see `alia_resolve_font`) and activates the resulting records.
typedef struct alia_resolved_font
{
    alia_resolved_typeface typeface;
    // logical (design) pixel size
    float size;
    // metrics for this font, in logical pixels
    alia_font_metrics metrics;
} alia_resolved_font;

// `alia_font_key` computes a 64-bit key that uniquely identifies a font for
// caching purposes. It is a packed combination of the typeface ID and size.
static inline uint64_t
alia_font_key(alia_font font)
{
    uint32_t size_bits;
    float const s = font.size;
    memcpy(&size_bits, &s, sizeof(size_bits));
    return ((uint64_t) font.typeface << 32) | (uint64_t) size_bits;
}

// Resolve a font to a cached record. The result is cached in the substrate at
// the call site. The font's typeface ID must be valid.
// The returned pointer points into the substrate, so it is safe to use
// anywhere within the current pass through the component subtree, but it
// shouldn't be stored across frames without proper lifetime consideration.
alia_resolved_font const*
alia_resolve_font(alia_context* ctx, alia_font font);

// Push a resolved font, making it the active font for the current scope.
void
alia_font_push(alia_context* ctx, alia_resolved_font const* font);

// Pop the active font, restoring the previous one.
void
alia_font_pop(alia_context* ctx);

// Return the active font.
// Asserts if there is no active font.
static inline alia_resolved_font const*
alia_active_font(alia_context* ctx)
{
    ALIA_ASSERT(ctx && ctx->active_font);
    return ctx->active_font;
}

// Get the active font's metrics. Asserts if there is no active font.
static inline alia_font_metrics const*
alia_active_font_metrics(alia_context* ctx)
{
    return &alia_active_font(ctx)->metrics;
}

// TEXT COMPONENT

// styling for a text element - The font is a pointer to a resolved font (NULL
// means inherit the active font). The color is palette-indexed like other UI
// components.
typedef struct alia_text_style
{
    // NULL => inherit the active font
    alia_resolved_font const* font;
    alia_palette_color color;
} alia_text_style;

// Fill `out` with the text style for `seeds`.
// Seeds can be `NULL` to use the default seeds.
void
alia_text_style_generate(alia_text_style* out, alia_style_seeds const* seeds);

static inline alia_text_style*
alia_text_style_default(alia_ui_system* ui)
{
    return (alia_text_style*) alia_style_default(ui, ALIA_STYLE_TEXT);
}

static inline alia_text_style*
alia_text_style_active(alia_context* ctx)
{
    return (alia_text_style*) alia_style_active(ctx, ALIA_STYLE_TEXT);
}

// Emit a text element.
// `flags` are layout flags.
// `style` may be null, in which case the active text style is used.
void
alia_text(
    alia_context* ctx,
    alia_layout_flags_t flags,
    alia_text_input_signal text,
    alia_text_style const* style);

ALIA_EXTERN_C_END

#endif /* ALIA_ABI_UI_TEXT_H */
