dist: bionic

language: python
python: 3.7

jobs:
  include:

  # Clang 4.0 testing job
  - env: CACHE_NAME=clang-4
    install:
    - sudo apt-get update -qy
    - sudo apt-get install -y --upgrade lcov git curl clang-4.0 llvm-4.0
    - sudo scripts/install-cmake.sh
    - scripts/set-up-travis.sh
    before_script:
    - export CC=`which clang-4.0`
    - export CXX=`which clang++-4.0`
    script:
    - scripts/do-ci-testing.sh

  # Clang 5.0 testing job - This also generates test coverage information.
  - env: CACHE_NAME=clang-5
    install:
    - sudo apt-get update -qy
    - sudo apt-get install -y --upgrade lcov git curl clang-5.0 llvm-5.0
    - sudo scripts/install-cmake.sh
    - scripts/set-up-travis.sh
    before_script:
    - export CC=`which clang-5.0`
    - export CXX=`which clang++-5.0`
    script:
    - scripts/do-ci-testing.sh
    after_success:
    - bash <(curl -s https://codecov.io/bash) -X gcov

  # GCC 5 testing job - This also deploys alia.hpp releases.
  - env: CACHE_NAME=gcc-5
    install:
    - sudo apt-get update -qy
    - sudo apt-get install -y --upgrade g++-5 gcc-5
    - sudo scripts/install-cmake.sh
    - scripts/set-up-travis.sh
    before_script:
    - export CC=`which gcc-5`
    - export CXX=`which g++-5`
    script:
    - scripts/do-ci-testing.sh
    deploy:
      provider: releases
      api_key:
        secure: ZrAOzBA2TtbVMcNg7UBjw5hP8D3mC2GxYSW05+bfYYOtNB6a41AonRhETBkIq5UfHMrKCEWy+tnvOcc6j1fQksiGYaSTbzRU8O51mmFSLKiBNuGTpN3Kro1hR0hqs3OZjKY9lp05OPdY9p++0UIwUFe68Yc+1dEdxqZi26nzt8Rpf34eblTyKb1dQZy0Hdn7dh5eUx0lTsuKA5GfUfDYKCMAmq30gnrbkOomuq7vtS5p2bm8D3NaX8bvoH372I5VDvRpXF91FPyGZfk04evOog9lPfICwq54/EnNtWeVvcLYgtDqSxMvdkjNwOwFLaAbK53lAlfHo4CSXYk0QcPqo6XoszQp1aj9gBY8pWHQzUu0D2XLFTwVg81J62iFDuXHoshe4Dv1rcDc8/Fwfqp16uUGfBPAzdxqjLVYWbHp6jevtC8+pNugOWGJC2C3xxIQZFX2k1qnOBxQ3PeEN1hwZ++UQOu0d/yTYl0SaPj3HLqO/hiVcZimx3q3nmIafBxtkPGUceM+EHU+4LWJGcE8cfqYemaAOkLuV53wR1xSGs96ftMOKrppmizAhjy4fmykIrEI62JnAV8CauMI/xwG0SYSs+s7oxL74C36rUKVCL1ib8wnyZVJfm61QLjSbPYxhU4UYs36QVIeVX03gnH3G06D44j0VDm1tBrJ+11ofbE=
      file: alia.hpp
      skip_cleanup: true
      on:
        tags: true
        repo: tmadden/alia

  # GCC 7 testing job
  - env: CACHE_NAME=gcc-7
    install:
    - sudo scripts/install-cmake.sh
    - scripts/set-up-travis.sh
    before_script:
    - export CC=`which gcc-7`
    - export CXX=`which g++-7`
    script:
    - scripts/do-ci-testing.sh

  # Emscripten job - This deploys the documentation.
  # (The isn't currently a full test. It just tests that the asm-dom examples
  # build successfully.)
  - env: CACHE_NAME=emscripten
    install:
    - sudo add-apt-repository universe
    - sudo apt-get update -qy
    - sudo apt install graphviz
    services:
    - docker
    script:
    - python scripts/generate-distributables.py
    - mv alia.hpp examples/asm-dom
    - mkdir examples/asm-dom/build
    - >
      docker run -it --name emscripten -v $(pwd)/examples/asm-dom:/src
      -w /src/build trzeci/emscripten:1.39.7-upstream
      bash -c 'emcmake cmake -DCMAKE_BUILD_TYPE=Release .. && make'
    - scripts/build-docs.sh
    deploy:
    - provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      on:
        branch: master
      local_dir: www
