sudo: required
dist: trusty

before_script:
  - sudo bash scripts/set-up-system.sh
  # Ubuntu Trusty has a buggy binutils.
  - sudo apt-get install -y --upgrade binutils-2.26
  - export PATH=/usr/lib/binutils-2.26/bin:${PATH}
  - scripts/set-up-python.sh
  - source .venv/bin/activate
  - export CC=`which clang-5.0`
  - export CXX=`which clang-5.0`
  - scripts/set-up-conan.sh
  - export CTEST_OUTPUT_ON_FAILURE=1

script:
  - ./fips make test linux-make-debug
  - ./fips make test linux-make-release

before_cache:
  - conan remove "*" -s -b -f

cache:
  directories:
  - $HOME/.conan/data

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
