dist: bionic

language: python
python: 3.7

jobs:
  include:

  # Clang 4.0 testing job
  - env: CACHE_NAME=clang-4
    install:
    - sudo apt-get update -qy
    - sudo apt-get install -y --upgrade lcov git curl clang-4.0 llvm-4.0
    - sudo scripts/install-cmake.sh
    - scripts/set-up-travis.sh
    before_script:
    - export CC=`which clang-4.0`
    - export CXX=`which clang++-4.0`
    script:
    - scripts/do-ci-testing.sh

  # Clang 5.0 testing job - This also generates test coverage information.
  - env: CACHE_NAME=clang-5
    install:
    - sudo apt-get update -qy
    - sudo apt-get install -y --upgrade lcov git curl clang-5.0 llvm-5.0
    - sudo scripts/install-cmake.sh
    - scripts/set-up-travis.sh
    before_script:
    - export CC=`which clang-5.0`
    - export CXX=`which clang++-5.0`
    script:
    - scripts/do-ci-testing.sh

  # GCC 5 testing job - This also deploys alia.hpp releases.
  - env: CACHE_NAME=gcc-5
    install:
    - sudo apt-get update -qy
    - sudo apt-get install -y --upgrade g++-5 gcc-5
    - sudo scripts/install-cmake.sh
    - scripts/set-up-travis.sh
    before_script:
    - export CC=`which gcc-5`
    - export CXX=`which g++-5`
    script:
    - scripts/do-ci-testing.sh
    - mkdir www && cp alia.hpp www

  # GCC 7 testing job
  - env: CACHE_NAME=gcc-7
    install:
    - sudo scripts/install-cmake.sh
    - scripts/set-up-travis.sh
    before_script:
    - export CC=`which gcc-7`
    - export CXX=`which g++-7`
    script:
    - scripts/do-ci-testing.sh
