# version string format -- This will be overwritten later anyway
version: "{build}"

image:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

install:
  # Set up Conan.
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user
  - conan --version
  - scripts\set-up-conan.bat

environment:
  BOOST_VERSION: 1_66_0
  BOOST_ROOT: C:/Libraries/boost_%BOOST_VERSION%

for:
  - matrix:
      only:
        - platform: x64
          configuration: Release
    before_build:
      - fips set config win64-vstudio-release
    environment:
      BOOST_LIBRARY_DIR: %BOOST_ROOT%/lib64-msvc-%VisualStudioVersion%
  - matrix:
      only:
        - platform: x64
          configuration: Debug
    before_build:
      - fips set config win64-vstudio-debug
    environment:
      BOOST_LIBRARY_DIR: %BOOST_ROOT%/lib64-msvc-%VisualStudioVersion%
  - matrix:
      only:
        - platform: x86
          configuration: Release
    before_build:
      - fips set config win32-vstudio-release
    environment:
      BOOST_LIBRARY_DIR: %BOOST_ROOT%/lib32-msvc-%VisualStudioVersion%
  - matrix:
      only:
        - platform: x86
          configuration: Debug
    before_build:
      - fips set config win32-vstudio-debug
    environment:
      BOOST_LIBRARY_DIR: %BOOST_ROOT%/lib32-msvc-%VisualStudioVersion%

build_script:
  - fips gen
  - fips make ctest
