# version string format -- This will be overwritten later anyway
version: "{build}"

image:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

branches:
  only:
    - master

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"
  - set VCVARSALL14="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - set VCVARSALL15="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat"
  - ps: |
      if ("$env:APPVEYOR_BUILD_WORKER_IMAGE" -eq "Visual Studio 2015") {
          $env:MSVCID = "msvc2015"
          $env:VCVARSALL = "$env:VCVARSALL14"
          $env:QT_VERSION = "5.11.3"
          $env:GENERATOR_BASE = "Visual Studio 14 2015"
      } else {
          $env:MSVCID = "msvc2017"
          $env:VCVARSALL = "$env:VCVARSALL15"
          $env:QT_VERSION = "5.13.2"
          $env:GENERATOR_BASE = "Visual Studio 15 2017"
      }
  - set QT_ROOT_DIR=C:\Qt\%QT_VERSION%

for:
  - matrix:
      only:
        - platform: x64
          configuration: Release
    before_build:
      - call %VCVARSALL% x64
      - set "GENERATOR=%GENERATOR_BASE% Win64"
      - set Qt5_DIR=%QT_ROOT_DIR%\%MSVCID%_64\lib\cmake\Qt5
    environment:
      LIBRARY_ARCHITECTURE: lib64
  - matrix:
      only:
        - platform: x64
          configuration: Debug
    before_build:
      - call %VCVARSALL% x64
      - set "GENERATOR=%GENERATOR_BASE% Win64"
      - set Qt5_DIR=%QT_ROOT_DIR%\%MSVCID%_64\lib\cmake\Qt5
    environment:
      LIBRARY_ARCHITECTURE: lib64
  - matrix:
      only:
        - platform: x86
          configuration: Release
    before_build:
      - call %VCVARSALL% x86
      - set "GENERATOR=%GENERATOR_BASE%"
      - set Qt5_DIR=%QT_ROOT_DIR%\%MSVCID%\lib\cmake\Qt5
    environment:
      LIBRARY_ARCHITECTURE: lib32
  - matrix:
      only:
        - platform: x86
          configuration: Debug
    before_build:
      - call %VCVARSALL% x86
      - set "GENERATOR=%GENERATOR_BASE%"
      - set Qt5_DIR=%QT_ROOT_DIR%\%MSVCID%\lib\cmake\Qt5
    environment:
      LIBRARY_ARCHITECTURE: lib32

build_script:
  - set CTEST_OUTPUT_ON_FAILURE=1
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G"%GENERATOR%" ..
  - ctest -C %CONFIGURATION%
  - cd ..
  # Also test the Qt sandbox.
  - C:\Python36\python scripts\generate-distributables.py
  - move alia.hpp examples\qt
  - cd examples\qt
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G"NMake Makefiles" ..
  - cmake --build .
