name: Clang

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:

  clang-16:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - uses: friendlyanon/setup-vcpkg@v1
      with:
        committish: 662dbb50e63af15baa2909b7eac5b1b87e86a0aa
        path: the-vcpkg

    - name: Install gcovr
      run: |
        sudo pip install gcovr

    - name: Configure
      run: |
        export CC=`which clang-16`
        export CXX=`which clang++-16`
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.config}} \
          -D"CMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
          -DALIA_ENABLE_INDIE=ON \
          -DALIA_ENABLE_GLFW=OFF \
          . \

    - name: Build
      run: >
        cmake --build build --config ${{matrix.config}}
        --target unit_test_runner indie_unit_test_runner -j4

    - name: Test
      run: |
        cd build
        ctest --build-config ${{matrix.config}}

  clang-10:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - uses: friendlyanon/setup-vcpkg@v1
      with:
        committish: 662dbb50e63af15baa2909b7eac5b1b87e86a0aa
        path: the-vcpkg

    - name: Install
      run: |
        sudo pip install gcovr

    - name: Configure
      run: |
        export CC=`which clang-10`
        export CXX=`which clang++-10`
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.config}} \
          -D"CMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
          -DALIA_ENABLE_INDIE=OFF \
          .

    - name: Build
      run: >
        cmake --build build --config ${{matrix.config}}
        --target unit_test_runner -j4

    - name: Test
      run: |
        cd build
        ctest --build-config ${{matrix.config}}

    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash) -X gcov
