name: Deployment

on:
  push:
    branches:
      - master

jobs:

  docs:
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo add-apt-repository universe
        sudo apt-get update -qy
        sudo apt install graphviz

    - name: Build
      run: >
        mkdir build

        docker run --name emscripten -v $(pwd):/alia-docs
        -w /alia-docs/build trzeci/emscripten:1.39.7-upstream
        bash -c 'emcmake cmake -DCMAKE_BUILD_TYPE=Release .. && make'

        scripts/build-docs.sh

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: www
        CLEAN: true
