name: GCC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:

  gcc-7:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        export CC=`which gcc-7`
        export CXX=`which g++-7`
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.config}} .

    - name: Build
      run: >
        cmake --build build --config ${{matrix.config}}
        --target unit_test_runner -j4

    - name: Test
      run: |
        cd build
        ctest --build-config ${{matrix.config}}

  gcc-10:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo apt install gcc-10

    - name: Configure
      run: |
        export CC=`which gcc-10`
        export CXX=`which g++-10`
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.config}} .

    - name: Build
      run: >
        cmake --build build --config ${{matrix.config}}
        --target unit_test_runner -j4

    - name: Test
      run: |
        cd build
        ctest --build-config ${{matrix.config}}
