name: HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  EM_VERSION: 3.1.40
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up cache
        id: emscripten-cache
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: emcache-${{env.EM_VERSION}}-${{ runner.os }}

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - uses: friendlyanon/setup-vcpkg@v1
        with:
          committish: b4624c3a701b11248d88aab08744a37ee7aea1cc
          path: the-vcpkg
          cache-version: gh-pages

      - name: Build
        run: |
          mkdir build
          cd build
          emcmake cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release \
            -D"VCPKG_CHAINLOAD_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" \
            -DVCPKG_TARGET_TRIPLET=wasm32-emscripten \
            -D"CMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DALIA_BUILD_DOCS=OFF \
            -DALIA_ENABLE_UI=OFF \
            ..
          make -j

      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          repository-name: alialib/alia-staging
          target-folder: html
          token: ${{ secrets.ALIA_GHPAGES_DEPLOYMENT_TOKEN }}
          branch: gh-pages
          folder: build/integrations/html/deploy
