name: Latest Deployment

on:
  push:
    branches:
      - main

jobs:

  alia-single-header:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        python3 scripts/generate-distributables.py
        mkdir build
        mv alia.hpp build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        CLEAN: true
        SINGLE_COMMIT: true
