name: MSVC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:

  VS2019:
    runs-on: windows-2019

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - uses: friendlyanon/setup-vcpkg@v1
      with:
        committish: 662dbb50e63af15baa2909b7eac5b1b87e86a0aa
        path: the-vcpkg

    - name: Configure
      run: >
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.config}}
        -D"CMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
        -DALIA_ENABLE_UI=ON
        -DALIA_ENABLE_GLFW=OFF
        .

    - name: Build
      run: >
        cmake --build build --config ${{matrix.config}}
        --target core_unit_test_runner ui_unit_test_runner -j4

    - name: Test
      run: |
        cd build
        ctest --build-config ${{matrix.config}}
