name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CONFIGURATION: Debug

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: test
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=%CONFIGURATION% .
        cmake --build build --target ctest
