name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{config}} .

    - name: Build tests
      run: |
        cmake --build build --config ${{config}} --target unit_test_runner -j4
        cmake --build build --config ${{config}} --target single_header_tester

    - name: Test
      run: |
        cmake --build build --config ${{config}} --target ctest
